### PR TITLE
Fix Browsersync html task reload issue

### LINKED ISSUE #251: Html not updating when there are too many pages
Hi

We have lots of pages and we noticed that the last ones (probably in alphabetical sorting) are not updated if the html should change (update in json or html).
To reproduce the issue you can use a clean clone and just copy the page.html file 100 times. Then you create a zpage.html and load this page in the browser. Then you open the zpage.html in an editor and change something... the page will not be updated in the browser and reloading does not help either.

I tested this on Windows 10 - a friend of mine is testing it on his mac now as well. Will update the ticket with the information soon.

### PR DESCRIPTION
**Pull request by mdmoreau**
Fixes #251
Only reload once at the end of the stream to keep browser from reloading too early

### CODE REVIEW

File: gulpfile.js/tasks/html.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ var htmlTask = function() {
     .on('error', handleErrors)
     .pipe(gulpif(global.production, htmlmin(config.tasks.html.htmlmin)))
     .pipe(gulp.dest(paths.dest))
-    .pipe(browserSync.stream())
+    .on('end', browserSync.reload)
```
Comment (greypants) [inline gulpfile.js/tasks/html.js]: How does this compare with doing

```js
.pipe(browserSync.stream({once: true}));
```

as outlined in the [docs](https://www.browsersync.io/docs/api#api-stream)?

Comment (mdmoreau) [inline gulpfile.js/tasks/html.js]: It sounds like that should work based on the docs, but I haven't noticed any difference when trying that method.  It doesn't seem to really matter until you have a lot of files or a longer nunjucks processing time, but once either of those are an issue using `.on('end', browserSync.reload)` is the only thing I've seen that consistently solves the problem.  Discussed it a little bit in #251, and it didn't sound like anyone else had luck with `stream: true` either.

**Comment by greypants** [comment]
Sounds good. Thanks for figuring that out!
